/* 
 * MskDotNet.Race API
 *
 * MskDotNet.Race
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// CreateRaceDto
    /// </summary>
    [DataContract]
    public partial class CreateRaceDto :  IEquatable<CreateRaceDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateRaceDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateRaceDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateRaceDto" /> class.
        /// </summary>
        /// <param name="map">map (required).</param>
        public CreateRaceDto(string map = default(string))
        {
            // to ensure "map" is required (not null)
            if (map == null)
            {
                throw new InvalidDataException("map is a required property for CreateRaceDto and cannot be null");
            }
            else
            {
                this.Map = map;
            }
        }
        
        /// <summary>
        /// Gets or Sets Map
        /// </summary>
        [DataMember(Name="Map", EmitDefaultValue=false)]
        public string Map { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateRaceDto {\n");
            sb.Append("  Map: ").Append(Map).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateRaceDto);
        }

        /// <summary>
        /// Returns true if CreateRaceDto instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateRaceDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateRaceDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Map == input.Map ||
                    (this.Map != null &&
                    this.Map.Equals(input.Map))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Map != null)
                    hashCode = hashCode * 59 + this.Map.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
