/* 
 * MskDotNet.Race API
 *
 * MskDotNet.Race
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;
using FirstBot.Model;

namespace IO.Swagger.Model
{
    /// <summary>
    /// TurnModel
    /// </summary>
    [DataContract]
    public partial class TurnModel :  IEquatable<TurnModel>, IValidatableObject
    {
       

        /// <summary>
        /// Player&#39;s desired direction.
        /// </summary>
        /// <value>Player&#39;s desired direction.</value>
        [DataMember(Name="Direction", EmitDefaultValue=false)]
        public DirectionEnum? Direction { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TurnModel" /> class.
        /// </summary>
        /// <param name="direction">Player&#39;s desired direction..</param>
        /// <param name="acceleration">Acceleration..</param>
        public TurnModel(DirectionEnum? direction = default(DirectionEnum?), int? acceleration = default(int?))
        {
            this.Direction = direction;
            this.Acceleration = acceleration;
        }
        

        /// <summary>
        /// Acceleration.
        /// </summary>
        /// <value>Acceleration.</value>
        [DataMember(Name="Acceleration", EmitDefaultValue=false)]
        public int? Acceleration { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TurnModel {\n");
            sb.Append("  Direction: ").Append(Direction).Append("\n");
            sb.Append("  Acceleration: ").Append(Acceleration).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TurnModel);
        }

        /// <summary>
        /// Returns true if TurnModel instances are equal
        /// </summary>
        /// <param name="input">Instance of TurnModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TurnModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Direction == input.Direction ||
                    (this.Direction != null &&
                    this.Direction.Equals(input.Direction))
                ) && 
                (
                    this.Acceleration == input.Acceleration ||
                    (this.Acceleration != null &&
                    this.Acceleration.Equals(input.Acceleration))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Direction != null)
                    hashCode = hashCode * 59 + this.Direction.GetHashCode();
                if (this.Acceleration != null)
                    hashCode = hashCode * 59 + this.Acceleration.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
